safe:			false
source:			.
destination:	_gh-pages
lsi:			false
permalink:		pretty
baseurl: 		"https://eadpucv.github.io/pix"
exclude:		[bower_components, src]
name: 			"PiX"
pixver:			"1.0.0"
exclude:
  - less
  - libs
  - node_modules
  - bower_components
  - src
  - bower.json
  - package.json
  - Makefile