title: "PiX - Partituras de Interacción"
safe:			false
source:			.
destination: docs
lsi: false
permalink: pretty
baseurl: 		""
url: "https://eadpucv.github.io/pix"
exclude:		[bower_components, src]
name: 			"PiX"
pixver:			"1.0.0"
exclude:
  - less
  - libs
  - node_modules
  - bower_components
  - src
  - bower.json
  - package.json
  - Makefile
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge