#!/usr/bin/env python3
"""Regenerate src/export/fonts.js — the IBM Plex Sans faces embedded in
SVG and PDF exports so they match the on-screen app anywhere, installed
or not.

The four faces are instantiated from the installed variable font
(@fontsource-variable/ibm-plex-sans, latin subset), so on-screen and
exported type come from one source:

    regular  wght 400  wdth 100
    bold     wght 700  wdth 100
    italic   wght 400  wdth 100  (from the italic file)
    cond     wght 400  wdth 80   — matches the cells' font-stretch:80%

Run from the editor package root, after `npm install`, in a venv with
fonttools + brotli:

    python3 -m venv /tmp/fontenv
    /tmp/fontenv/bin/pip install fonttools brotli
    /tmp/fontenv/bin/python scripts/build-export-fonts.py

The output (src/export/fonts.js) is committed; only rerun it when the
faces or the source font change.
"""
import base64, json, os
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
REL = "node_modules/@fontsource-variable/ibm-plex-sans/files"


def _find_base():
    # npm workspaces usually hoist the dependency to the repo root, but
    # it may also resolve inside the package. Accept either.
    for root in (PKG, os.path.dirname(os.path.dirname(PKG))):
        cand = os.path.join(root, REL)
        if os.path.isdir(cand):
            return cand
    raise SystemExit(
        f"Could not find {REL} — run `npm install` first "
        "(checked the package and the repo root)."
    )


BASE = _find_base()
NORMAL = os.path.join(BASE, "ibm-plex-sans-latin-standard-normal.woff2")
ITALIC = os.path.join(BASE, "ibm-plex-sans-latin-standard-italic.woff2")
OUT = os.path.join(PKG, "src/export/fonts.js")

# key, css family, cssWeight, cssStyle, jsPDF styleId, source, axes
FACES = [
    ("regular", "IBM Plex Sans",      400, "normal", "normal", NORMAL, {"wght": 400, "wdth": 100}),
    ("bold",    "IBM Plex Sans",      700, "normal", "bold",   NORMAL, {"wght": 700, "wdth": 100}),
    ("italic",  "IBM Plex Sans",      400, "italic", "italic", ITALIC, {"wght": 400, "wdth": 100}),
    ("cond",    "IBM Plex Sans Cond", 400, "normal", "normal", NORMAL, {"wght": 400, "wdth": 80}),
]


def instance_ttf(src, axes, family, subfamily):
    f = TTFont(src)
    instantiateVariableFont(f, axes, inplace=True)
    name = f["name"]
    for nid, val in [(1, family), (2, subfamily), (4, f"{family} {subfamily}"),
                     (6, f"{family.replace(' ', '')}-{subfamily.replace(' ', '')}"),
                     (16, family), (17, subfamily)]:
        name.setName(val, nid, 3, 1, 0x409)
    f.flavor = None  # plain TTF, jsPDF cannot read woff2
    import io
    buf = io.BytesIO()
    f.save(buf)
    return buf.getvalue()


def main():
    rows = []
    for key, family, w, st, pdf, src, axes in FACES:
        sub = "Italic" if st == "italic" else ("Bold" if w == 700 else "Regular")
        ttf = instance_ttf(src, axes, family, sub)
        b64 = base64.b64encode(ttf).decode()
        rows.append((key, family, w, st, pdf, b64))

    L = [
        "// Auto-generated by scripts/build-export-fonts.py — do not edit by hand.",
        "// IBM Plex Sans static instances (latin subset) for self-contained exports,",
        "// instantiated from @fontsource-variable/ibm-plex-sans:",
        "//   regular  wght 400 wdth 100",
        "//   bold     wght 700 wdth 100",
        "//   italic   wght 400 wdth 100 (italic)",
        "//   cond     wght 400 wdth 80  — matches the on-screen cell font-stretch:80%",
        "// ~228KB raw; imported only inside export code paths, so it lands in a lazy",
        "// chunk and never touches first paint.",
        "",
        "export const FONTS = [",
    ]
    for key, family, w, st, pdf, b64 in rows:
        L.append(f"  {{ key: {json.dumps(key)}, family: {json.dumps(family)}, "
                 f"cssWeight: {w}, cssStyle: {json.dumps(st)}, "
                 f"pdfStyle: {json.dumps(pdf)}, filename: {json.dumps(key + '.ttf')}, b64:")
        L.append(f'    "{b64}" }},')
    L += [
        "];",
        "",
        "// A <style> block embedding the faces as data-URIs, so an exported SVG",
        "// opened anywhere renders in IBM Plex Sans without the font installed.",
        "export function fontFaceCss() {",
        "  return FONTS.map(f =>",
        "    `@font-face{font-family:'${f.family}';font-weight:${f.cssWeight};` +",
        "    `font-style:${f.cssStyle};` +",
        "    `src:url(data:font/ttf;base64,${f.b64}) format('truetype');}`",
        "  ).join('');",
        "}",
        "",
        "// Register the faces into a jsPDF document so svg2pdf and doc.text render",
        "// in IBM Plex Sans instead of the PDF core Helvetica. Call once per document.",
        "export function registerPdfFonts(doc) {",
        "  for (const f of FONTS) {",
        "    doc.addFileToVFS(f.filename, f.b64);",
        "    doc.addFont(f.filename, f.family, f.pdfStyle);",
        "  }",
        "}",
    ]
    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
